### ISSUE TITLE
Invalid manifest

### ISSUE THREAD

**Issue by m35** [majgis/ChromeExtension_HighlightAll#19]
Trying to install this extension from the Chrome web store results in an error
> An error has occurred
> There was a problem with the download. Please contact the developer or try again later.
> Show Details
> Invalid manifest

The `manifest.json` needs to be updated 
* with `"manifest_version": 2`
* and `background_page` should now just be `background`

`htm/popup.htm` shouldn't have inline JavaScript

There are probably other changes necessary but those are just the first few I found.

I like this extension. Just reporting it here in case others run into the same issue and wonder why.

**Comment by liango2** [comment]
I also encountered the same problem

**Comment by m35** [comment]
Actually I see these changes have been made on the (unreleased) master branch https://github.com/majgis/ChromeExtension_HighlightAll/tree/38a8efb53cc5050eeab9d13eb0ed22c036ab3d9a

I tried loading that branch in Chrome (load unpacked extension) but something still isn't quite right about it. It stops highlight on a page after some time.

**Comment by liango2** [comment]
this chrome extension can't work for a long time, I can't recover it perfectly. please help

**Comment by majgis** [comment]
I've switched to firefox and not inspired to keep maintaining this plugin.  Please consider forking and publishing yourself.
